const es = {
    translation: {
        "ID": "ID",
        "si": "Sí",
        "no": "No",
        "o": "o",
        "cargando": "Cargando...",
        "cerrar": "Cerrar",
        "finalizada": "Finalizada",
        "no-resultados": "No se encontraron resultados",
        "accion": "Acción realizada",
        "usuario-incidido": "Usuario incidido",
        "archivos-relacionados": "Archivos relacionados",
        "caracteres-maximos": "Máximo 400 caracteres",
        "seleccionar-archivo": "Seleccionar archivo",
        "archivo": "Archivo",
        "cancelar": "Cancelar",
        "enviar": "Enviar",
        "opcional": "(opcional)",
        "indice-tic": "Índice de apropiación TIC",
        "usuarios": "Usuarios",
        "docentes": "Docentes",
        "instituciones": "Instituciones Educativas",
        "instituciones-corto": "Instituciones",
        "establecimientos": "Establecimientos Educativos",
        "establecimientos-corto": "Establecimientos",
        "gobiernos": "Gobiernos",
        "evaluadores": "Evaluadores",
        "admins": "Admins",
        "barrio": "Barrio",
        "localidad": "Localidad",
        "vereda": "Vereda",
        "corregimiento": "Corregimiento",
        "rural": "Rural",
        "urbana": "Urbana",
        "oficial": "Oficial",
        "privado": "Privado",
        "concesion": "Concesión",
        "nombre": "Nombre",
        "calificacion": "Calificación",
        "descriptor": "Descriptor",
        "descriptores": "Descriptores",
        "descripcion": "Descripción",
        "definicion": "Definición",
        "de": "de",
        "pregunta": "Pregunta",
        "respuesta": "Respuesta",
        "respuestas": "Respuestas",
        "ver-data": "Ver información relacionada",
        "id-evento": "ID del evento",
        "filasPorPagina": "Filas por página",
        "buscar": "Buscar...",
        "escribir": "Escribir...",
        "fecha-realizacion": "Fecha de realización",
        "editar-calificacion": "Editar calificación",
        "revisar": "Revisar",
        "volver-inicio": "Volver a inicio",
        "imagen-perfil": "Imagen de perfil",
        "actividades": "Actividades",
        "descargar-certificado": "Descargar certificado",
        "descargar-resultados": "Descargar resultados",
        "salir.no-guardar-terminar": "¿Está seguro de que desea salir sin guardar o terminar? Todos los cambios realizados se perderán.",
        "salir.no-terminar": "¿Está seguro de que desea salir sin terminar? Todos los cambios realizados se perderán.",
        "salir.confirmar": "Confirmación",
        "salir.si": "Salir",
        "salir.no": "Cancelar y quedarme",
        "login.titulo": "Inicio de sesión",
        "login.usuario": "Usuario",
        "login.contrasenia": "Contraseña",
        "login.btn": "Ingresar",
        "login.registro": "¿Docente independiente? (sin asociación con ninguna institución educativa)",
        "login.registro-link": "Regístrese aquí",
        "login.no-recuerda": "¿No recuerda su usuario o contraseña?",
        "link.login": "login",
        "link.recuperacion-datos": "recuperacion-datos",
        "link.registro": "registro",
        "link.primer-ingreso": "primer-ingreso",
        "link.dashboard": "dashboard",
        "link.dashboard-docente": "dashboard-docente",
        "link.dashboard-ie": "dashboard-ie",
        "link.dashboard-ee": "dashboard-ee",
        "link.dashboard-gobierno": "dashboard-gobierno",
        "link.dashboard-evaluador": "dashboard-evaluador",
        "link.dashboard-admin": "dashboard-admin",
        "link.dashboard-superadmin": "dashboard-superadmin",
        "link.prueba": "prueba",
        "link.practica": "practica",
        "link.preentrevista": "preentrevista",
        "link.entrevista": "entrevista",
        "link.encuesta": "encuesta",
        "link.configuracion": "configuracion",
        "link.usuarios": "usuarios",
        "link.procesos": "procesos",
        "link.territorios": "territorios",
        "link.practica-revision": "practica-revision",
        "link.preentrevista-revision": "preentrevista-revision",
        "link.entrevista-revision": "entrevista-revision",
        "link.encuesta-revision": "encuesta-revision",
        "link.calificaciones": "calificaciones",
        "link.instrumento": "instrumento",
        "link.auditoria": "auditoria",
        "link.ayuda": "ayuda",
        "link.cursos": "cursos",
        "titulo.primerIngreso": "Primer ingreso - Cambie su contraseña",
        "titulo.no-login": "Inicio de sesión | Plataforma de Competencias TIC",
        "titulo.recuperacion-datos": "Recuperación de datos",
        "titulo.nombre-plataforma": "Plataforma de Competencias TIC",
        "titulo.calificaciones": "Calificaciones",
        "titulo.inicio": "Inicio",
        "titulo.configuracion": "Configuracion",
        "titulo.404": "Página no encontrada",
        "titulo.practica-revision": "Revisión de Práctica Educativa",
        "titulo.preentrevista-revision": "Revisión de Pre-entrevista",
        "titulo.entrevista-revision": "Revisión de Entrevista",
        "titulo.encuesta-revision": "Revisión de Encuesta",
        "titulo.ayuda": "Ayuda",
        "titulo.encuesta": "Encuesta",
        "titulo.cursos": "Cursos en la plataforma",
        "incipiente": "Incipiente",
        "en-desarrollo": "En Desarrollo",
        "establecido": "Establecido",
        "integracion": "Integración",
        "reorientacion": "Reorientación",
        "evolucion": "Evolución",
        "estado-actual": "Estado actual",
        "recuperacionDatos.titulo": "Recuperación de datos",
        "recuperacionDatos.ayuda": "Digite la dirección de correo electrónico asociada a su cuenta. Le enviaremos un enlace con el que podrá actualizar sus credenciales en la plataforma.",
        "recuperacionDatos.mensaje-correcto": "¡Correo enviado exitosamente!",
        "recuperacionDatos.mensaje-error": "¡Correo no encontrado!",
        "recuperacionDatos.regresar": "Regresar al inicio de sesión",
        "primerIngreso.titulo": "Cambiar contraseña",
        "loginCheck.mensaje-navbar": "Plataforma de competencias TIC",
        "dashboardGobierno.division": "Actualmente viendo datos de:",
        "dashboardGobierno.general": "Información general",
        "dashboardGobierno.indice": "Índice de apropiación TIC",
        "dashboardGobierno.instituciones": "Instituciones educativas",
        "dashboardGobierno.establecimientos": "Establecimientos educativos",
        "dashboardGobierno.docentes": "Docentes",
        "dashboardGobierno.descriptores": "Estado de descriptores",
        "dashboardGobierno.niveles": "Estado de niveles",
        "dashboardGobierno.frecuencia-absoluta": "Frecuencia absoluta",
        "dashboardGobierno.frecuencia-relativa": "Frecuencia relativa",
        "dashboardGobierno.distribucion-relativa": "Distribución relativa",
        "dashboardGobierno.detallada": "Información detallada",
        "dashboardGobierno.ruta": "Ruta de aprendizaje sugerida",
        "visorPerfiles.todos": "Ver todos",
        "visorPerfiles.anteriores": "◀ Anteriores",
        "visorPerfiles.siguientes": "Siguientes ▶",
        "visorPerfiles.no-resultados": "No se encontraron resultados",
        "perfil.ingreso": "Último ingreso:",
        "perfil.nunca": "nunca ha ingresado",
        "perfil.ver-detalles": "Ver detalles",
        "perfil.num-docentes": "Número de docentes:",
        "perfil.num-sedes": "Número de establecimientos:",
        "perfil.num-instituciones": "Número de instituciones:",
        "perfil.num-encuestas": "Encuestas asignadas:",
        "perfil.num-practicas": "Prácticas asignadas:",
        "perfil.num-preentrevistas": "Pre-entrevistas asignadas:",
        "perfil.num-entrevistas": "Entrevistas asignadas:",
        "perfil.pais": "País:",
        "procesoPaso.0": "Registro de datos",
        "procesoPaso.1": "Prueba de conocimientos",
        "procesoPaso.2": "Prácticas educativas",
        "procesoPaso.3": "Pre-entrevista",
        "procesoPaso.3-plural": "Pre-entrevistas",
        "procesoPaso.4": "Entrevista",
        "procesoPaso.4-plural": "Entrevistas",
        "procesoPaso.5": "Encuestas",
        "practicas.titulo": "Práctica Educativa",
        "practicas.label-informacion-general": "Información general",
        "practicas.informacion-general": 'A continuación, se le pedirá información sobre una práctica educativa apoyada en TIC. Se entiende por práctica educativa "la actividad o conjunto de actividades intencionalmente diseñadas, implementadas y evaluadas por agentes educativos para favorecer la apropiación de conocimiento". Tenga en cuenta que una práctica educativa puede implicar actividades para explorar conocimientos previos, presentar contenidos, brindar oportunidades de práctica y evaluar el aprendizaje.',
        "practicas.nombre": "Nombre de la práctica educativa",
        "practicas.resenia": "Reseña",
        "practicas.ayuda-resenia": "Mencione brevemente el objetivo de enseñanza, personas a quienes está dirigida la práctica, principales recursos tecnológicos utilizados, generalidad del procedimiento utilizado, resultado o conclusión principal.",
        "practicas.tags": "Palabras clave",
        "practicas.ayuda-tags": "Escriba al menos 5 palabras clave",
        "practicas.btn-agregar": "Agregar",
        "practicas.poblacion": "Población",
        "practicas.ayuda-poblacion": "Personas directamente beneficiadas por la práctica educativa",
        "practicas.niveles": "¿A qué niveles educativos está dirigida la práctica educativa?",
        "practicas.num-personas": "Cantidad de personas",
        "practicas.num-grupos": "Cantidad de grupos",
        "practicas.num-personas-grupo": "Personas por grupo",
        "practicas.ayuda-edad": "En general, ¿Cuál es la edad de los estudiantes que participan en su práctica educativa?",
        "practicas.label-rango": "Seleccione un rango *",
        "practicas.necesidades-especiales": "¿La práctica atiende población con necesidades educativas especiales?",
        "practicas.que-necesidades-especiales": "¿A qué necesidades educativas especiales atiende la práctica educativa?",
        "practicas.seleccione-necesidad-especial": "Seleccione la necesidad especial *",
        "practicas.otras-necesidades-cuales": "¿Cuáles?",
        "practicas.area": "Área Disciplinar",
        "practicas.ayuda-area": "¿En qué áreas disciplinares hace énfasis su práctica educativa apoyada en TIC?",
        "practicas.label-descripcion-detallada": "Descripción detallada de la práctica educativa",
        "practicas.necesidad-problema": "¿A qué necesidad o problema atiende su práctica educativa apoyada en TIC?",
        "practicas.ayuda-necesidad-problema": "Las razones que justifican su práctica.",
        "practicas.principal-objetivo": "¿Cuál es el principal objetivo de aprendizaje de la práctica educativa?",
        "practicas.ayuda-principal-objetivo": "La competencia que espera formar en sus estudiantes al finalizar la práctica educativa.",
        "practicas.label-resultados": "¿Cuáles son los resultados de aprendizaje esperados a partir de la práctica educativa?",
        "practicas.resultados": "Los desempeños y productos de los estudiantes como consecuencia de la participación en la práctica educativa.",
        "practicas.label-actividades": "A continuación, describa la o las actividades que propone para lograr el objetivo de aprendizaje.",
        "practicas.label-actividades-agregadas": "Actividades agregadas",
        "practicas.btn-agregar-actividad": "Agregar actividad",
        "practicas.label-checkbox": "Aseguro que la información proveída es correcta y completa.",
        "practicas.btn-enviar": "Enviar práctica educativa",
        "practicas.label-detalles-actividad": "Detalles de la actividad",
        "practicas.ayuda-detalles-actividad": "Complete los campos mostrados a continuación.",
        "practicas.elemento": "Elemento",
        "practicas.descripcion-contenido": "Descripción del contenido",
        "practicas.actividad-nombre": "Nombre de la actividad",
        "practicas.actividad-proposito": "Propósito",
        "practicas.actividad-modalidad-trabajo": "Modalidad de trabajo *",
        "practicas.actividad-grupal": "Grupal",
        "practicas.actividad-individual": "Individual",
        "practicas.actividad-mixta": "Mixta",
        "practicas.actividad-materiales-educativos": "Materiales educativos",
        "practicas.actividad-escenarios": "Escenarios",
        "practicas.actividad-procedimientos": "Procedimientos",
        "practicas.actividad-consigna": "Consigna",
        "practicas.actividad-evalua": "¿Evalúa las producciones de los estudiantes?",
        "practicas.actividad-label-evaluar-desempenio": "¿Qué hace para evaluar los desempeños de los estudiantes?",
        "practicas.actividad-describa-proceso": "Describa el proceso",
        "practicas.actividad-label-adjunte-evidencias": "Adjunte evidencia(s) de la(s) actividad(es) *",
        "practicas.actividad-ayuda-evidencias": "Sólo se aceptan archivos de imagen, video, audio, .doc, .docx, .xlsm, .xlsx, .pdf, .txt, .ppt y .pptx",
        "practicas.actividad-label-adjunte-produccion": "Adjunte la producción de un estudiante retroalimentada, si la tiene.",
        "practicas.actividad-ayuda-adjunte-produccion": "Recuerde borrar cualquier referencia a la identidad del estudiante.",
        "practicas.actividad-btn-agregar": "Agregar actividad",
        "practicas.enviada": "Práctica educativa enviada",
        "practicas.enviada-ayuda": "La información de su práctica educativa ha sido cargada exitosamente.",
        "preentrevista.titulo": "Pre-entrevista",
        "preentrevista.ayuda": "Por favor responda todas las preguntas que a continuación encontrará. Éstas buscan ahondar en su apropiación de compentencias TIC clave de su proceso docente.",
        "preentrevista.enviada": "Pre-entrevista enviada",
        "preentrevista.enviada-ayuda": "La información de su pre-entrevista ha sido cargada exitosamente.",
        "404.subtitulo": "404",
        "404.titulo": "Página no encontrada",
        "404.btn": "Regresar a inicio",
        "prueba.titulo": "Prueba de conocimientos previos",
        "prueba.pausar": "Guardar y pausar prueba",
        "prueba.label-introduccion": "Introducción",
        "prueba.introduccion": "Esta es una prueba para evaluar el conocimiento acerca del diseño, implementación y evaluación de prácticas educativas con TIC.",
        "prueba.label-instrucciones": "Instrucciones",
        "prueba.instrucciones": "A continuación, encontrará 31 preguntas de opción múltiple con única respuesta. Cada pregunta está constituida por un enunciado y cuatro (4) opciones de respuesta. Seleccione la opción que considere más correcta. Esta prueba debe ser finalizada una vez se inicia. Puede tomarse hasta una hora y treinta minutos (1:30) para responder. La resolución de la prueba es estrictamente individual.",
        "prueba.btn-iniciar": "Iniciar prueba",
        "prueba.titulo-cuestionario": "Cuestionario de preguntas",
        "prueba.btn-enviar": "Enviar respuestas",
        "prueba.label-tiempo": "Tiempo restante:",
        "prueba.label-resultados": "Resultados",
        "prueba.label-ayuda-resultados": "La prueba ha finalizado. A continuación podrá encontrar sus resultados.",
        "prueba.label-correctas": "Preguntas correctas:",
        "prueba.label-incorrectas": "Preguntas incorrectas:",
        "prueba.btn-volver-inicio": "Volver a inicio",
        "registro.titulo-principal": "Registro de datos",
        "registro.titulo": "Datos personales",
        "registro.nombres": "Nombres",
        "registro.apellidos": "Apellidos",
        "registro.fecha-nacimiento": "Fecha de nacimiento",
        "registro.descripcion-personal": "Descripción personal",
        "registro.label-educacion": "Educación formal máxima (alcanzada o en curso) *",
        "registro.educacion-bachiller": "Bachiller",
        "registro.educacion-tecnico": "Técnico",
        "registro.educacion-tecnologo": "Tecnólogo",
        "registro.educacion-profesional": "Profesional",
        "registro.educacion-especialista": "Especialista",
        "registro.educacion-magister": "Magister",
        "registro.educacion-doctorado": "Doctorado",
        "registro.educacion-postdoctorado": "Posdtoctorado",
        "registro.label-anios-experiencia": "¿Cuántos años tiene de experiencia docente?",
        "registro.experiencia-0": "No tengo experiencia",
        "registro.experiencia-1": "Entre 1 y 5",
        "registro.experiencia-2": "Entre 5 y 10",
        "registro.experiencia-3": "Entre 10 y 15",
        "registro.experiencia-4": "Más de 15 años",
        "registro.representa-ie": "¿Representa a una institución educativa? *",
        "registro.cual-label-otra": "Otra",
        "registro.directivo-otra-error": "Por favor consulte con su Insitución Educativa para que primero se realice su registro.",
        "registro.label-directivo": "¿Es directivo docente? *",
        "registro.label-tipo-directivo": "Tipo de directivo docente *",
        "registro.rector": "Rector",
        "registro.director": "Director",
        "registro.coordinador": "Coordinador",
        "registro.label-niveles": "¿En qué niveles enseña?",
        "registro.no-aplica": "No aplica",
        "registro.preescolar": "Preescolar",
        "registro.primaria": "Básica primaria",
        "registro.secundaria": "Básica secundaria",
        "registro.academica": "Media académica",
        "registro.tecnica": "Media técnica",
        "registro.label-areas": "Señale en qué áreas disciplinares trabaja en el establecimiento educativo - puede elegir más de una opción.",
        "registro.naturales": "Ciencias naturales y educación ambiental",
        "registro.sociales": "Ciencias sociales, historia, geografía y constitución política y democraciadia",
        "registro.arte": "Educación artística y cultural",
        "registro.etica": "Educación ética y en valores humanos",
        "registro.deporte": "Educación física, recreación y deporte",
        "registro.religion": "Educación Religiosa",
        "registro.humanidades": "Humanidades (lengua castellana e idiomas extranjeros)",
        "registro.matematicas": "Matemáticas",
        "registro.informatica": "Tecnología e informática",
        "registro.label-areas-otras": "Otra(s)",
        "registro.areas-otras": "¿Cuál(es)?",
        "registro.label-datos-perfil": "Datos de perfil",
        "registro.usuario": "Usuario",
        "registro.contrasenia": "Contrasenia",
        "registro.label-img-perfil": "Adjunte una imagen de perfil",
        "registro.email": "Correo electrónico",
        "registro.num-contacto": "Número de contacto",
        "registro.web-personal": "Página web personal",
        "registro.btn-guardar": "Registrarse",
        "registro.login": "¿Ya está registrado en un establecimiento educativo?",
        "registro.login-link": "Ingrese aquí",
        "entrevista.titulo": "Evidencias requeridas",
        "entrevista.ayuda": "Señor(a) docente, por favor prepare los siguientes recursos para presentar durante su próxima sesión de entrevista.",
        "entrevista.label-no-evaluado": "Su pre-entrevista aún no ha sido evaluada.",
        "entrevista.ayuda-no-evaluado": "Tan pronto se realice este proceso, se le notificará via correo electrónico con los recursos que deberá presentar durante la entrevista. Igualmente, revise periódicamente esta página.",
        "entrevista.no-requerido": "No requiere de entrevista",
        "entrevista.ayuda-no-requerido-0": "Señor(a) docente, tras evaluar su pre-entrevista, se ha determinado que no es necesario que pase a una entrevista.",
        "entrevista.ayuda-no-requerido-1": "Lo invitamos a analizar sus resultados e implementar las acciones de mejora correspondientes.",
        "entrevista.ayuda-no-requerido-2": "Igualmente, a volver a realizar todo el proceso cuando lo considere pertinente, para poder evaluar el progreso de su apropiación en competencias TIC.",
        "dashboardEE.label-encuestas": "Encuestas de autoevaluación sin responder",
        "dashboardEE.label-docentes": "Estado de docentes",
        "dashboardEE.factor": "Factor",
        "dashboardEE.responder": "Responder",
        "dashboardEE.encuesta-no-asignada": "Asignar",
        "dashboardEE.docentes": "Docentes",
        "dashboardEE.nunca-ingreso": "Nunca han ingresado",
        "dashboardEE.label-estado-general": "Estado general de procesos",
        "dashboardEE.label-frecuencia-absoluta": "Frecuencia absoluta",
        "dashboardEE.label-frecuencia-relativa": "Frecuencia relativa",
        "dashboardEE.ruta": "Ruta de aprendizaje sugerida",
        "dashboardDocente.encuestas-asignadas": "Encuestas institucionales asignadas",
        "dashboardDocente.proceso-actual": "Proceso actual",
        "dashboardDocente.cancelar-proceso-actual": "Cancelar proceso actual",
        "dashboardDocente.cancelar-proceso-actual-titulo": "¿Está seguro de que desea cancelar su proceso actual?",
        "dashboardDocente.cancelar-proceso-actual-ayuda": "Todos los datos que no haya enviado se perderán, y a las etapas que no haya completado se le asignarán las calificaciones mínimas, como sea el caso.",
        "dashboardDocente.cancelar-proceso-actual-ayuda-2": "Esto significa que el proceso no va a ser eliminado o dejado de tener en cuenta para sus cálculos históricos.",
        "dashboardDocente.cancelar-confirmacion": "Sí, cancelar mi proceso actual",
        "dashboardDocente.cancelar-no": "No, volver",
        "dashboardDocente.label-continuar": "Continuar con:",
        "dashboardDocente.mensaje-terminado": "Ha terminado el proceso actual exitosamente. Ya puede iniciar otro cuando lo considere conveniente.",
        "dashboardDocente.diagnostico": "Diagnóstico personal",
        "dashboardDocente.resultados-pruebas": "Resultados de pruebas",
        "dashboardDocente.ruta": "Ruta de aprendizaje sugerida",
        "dashboardDocente.no-data": "Aún no hay datos para mostrar",
        "dashboardDocente.acciones": "Acciones",
        "dashboardDocente.btn-registro": "Ver datos personales",
        "dashboardDocente.btn-prueba": "Ver prueba de conocimientos",
        "dashboardDocente.btn-datos": "Ver datos personales",
        "dashboardDocente.btn-practica": "Ver práctica educativa",
        "dashboardDocente.btn-preentrevista": "Ver pre-entrevista",
        "dashboardDocente.btn-entrevista": "Ver entrevista",
        "dashboardEvaluador.asignado-revision": "Asignado para revisión el:",
        "dashboardEvaluador.datos-contacto": "Datos de contacto",
        "dashboardEvaluador.distribucion-asignaciones": "Distribución de asignaciones vigentes",
        "dashboardEvaluador.revisiones": "Revisiones completadas vs vigentes",
        "dashboardEvaluador.revisiones-completadas": "Completadas",
        "dashboardEvaluador.revisiones-en-espera": "Vigentes",
        "dashboardEvaluador.respondido-por": "Respondido por:",
        "curso.imagen-alt": "Imagen relativa al curso",
        "configuracion.titulo": "Configuración",
        "configuracion.ajustes-plataforma": "Ajustes personales",
        "configuracion.parametros-plataforma": "Parámetros de la plataforma",
        "configuracion.formatos": "Formatos permitidos para cargar archivos",
        "configuracion.formatos-actuales": "Formatos actuales:",
        "configuracion.tamanio-archivos": "Tamaño máximo para archivos cargados (Bytes)",
        "configuracion.sitekey": "Google reCAPTCHA sitekey",
        "configuracion.encuestas": "Responder encuestas por",
        "configuracion.encuestas-institucion": "Institución",
        "configuracion.encuestas-sedes": "Sedes / Establecimientos",
        "configuracion.label-rol": "Ver plataforma como",
        "configuracion.label-version": "Versión del instrumento",
        "configuracion.label-idioma": "Idioma de la interfaz",
        "configuracion.ajustes-cuenta": "Información de la cuenta",
        "configuracion.label-imagen": "Imagen de perfil",
        "configuracion.label-usuario": "Nombre de usuario",
        "configuracion.label-contrasenia": "Contraseña",
        "configuracion.label-eliminar": "Desactivar cuenta",
        "configuracion.label-eliminar-confirmacion": "¿Está seguro(a) de que desea desactivar su cuenta?",
        "configuracion.label-eliminar-confirmacion-2": "Todas las cuentas que se encuentren asociadas a la suya también serán desactivadas.",
        "configuracion.btn-actualizar": "Actualizar datos",
        "configuracion.label-radio": "Sí, estoy seguro(a) de que quiero desactivar mi cuenta.",
        "configuracion.label-btn-eliminar": "Desactivar mi cuenta",
        "configuracion.label-personal": "Información personal",
        "configuracion.nombres": "Nombres",
        "configuracion.apellidos": "Apellidos",
        "configuracion.fecha-nacimiento": "Fecha de nacimiento",
        "configuracion.educacion-maxima": "Educación formal máxima (alcanzada o en curso)",
        "configuracion.descripcion-personal": "Descripción personal",
        "configuracion.anios-experiencia": "Años de experiencia docente",
        "configuracion.representa-ie": "¿Representa a una institución educativa?",
        "configuracion.representa-ie-cual": "¿Cuál?",
        "configuracion.es-directivo": "¿Es directivo docente?",
        "configuracion.tipo-directivo": "Tipo de directivo docente",
        "configuracion.niveles": "¿En qué niveles enseña?",
        "configuracion.areas": "¿En qué áreas disciplinares trabaja en el establecimiento educativo?",
        "configuracion.areas-otras-cuales": "¿Cuál(es)?",
        "usuarios.titulo": "Usuarios",
        "usuarios.label-registro-admins": "Registrar Administradores",
        "usuarios.label-registro-evaluadores": "Registrar Evaluadores y Gobiernos",
        "usuarios.label-registro-instituciones": "Registrar Instituciones",
        "usuarios.label-usuarios-admins": "Lista de Administradores",
        "usuarios.label-usuarios-evaluadores": "Lista de Evaluadores",
        "usuarios.label-usuarios-gobiernos": "Lista de Gobiernos",
        "usuarios.label-usuarios-instituciones": "Lista de Instituciones",
        "usuarios.registro-pais": "País",
        "usuarios.registro-departamento": "Provincia, Estado o Departamento",
        "usuarios.registro-btn-agregar": "Crear usuarios",
        "usuarios.registro-municipio": "Municipio o Ciudad",
        "usuarios.registro-nombre-ie": "Nombre",
        "usuarios.registro-idNacional": "ID Nacional",
        "usuarios.label-registro-establecimientos": "Registrar Establecimientos",
        "usuarios.label-usuarios-establecimientos": "Lista de Establecimientos",
        "usuarios.registro-ee-id": "ID Nacional",
        "usuarios.registro-ee-nombre": "Nombre",
        "usuarios.registro-ee-departamento": "Departamento",
        "usuarios.registro-ee-direccion": "Dirección",
        "usuarios.registro-ee-tipo-ubicacion": "Tipo de ubicación",
        "usuarios.registro-ee-nombre-ubicacion": "Nombre de la ubicación",
        "usuarios.registro-ee-zona": "Zona",
        "usuarios.registro-ee-regimen": "Régimen",
        "usuarios.registro-ee-telefono": "Teléfono",
        "usuarios.registro-ee-email": "Correo electrónico institucional",
        "usuarios.registro-ee-web": "Sitio web",
        "usuarios.label-registro-docentes": "Registrar Docentes",
        "usuarios.label-usuarios-docentes": "Lista de Docentes",
        "usuarios.registro-nombre-docente": "Nombre completo",
        "usuarios.registro-idEstablecimiento": "ID Nacional de la sede a la que pertenece",
        "usuarios.registro-idInstitucion": "ID Nacional de la institución a la que pertenece",
        "usuarios.registro-nombreInstitucion": "Nombre de la institución a la que pertenece",
        "usuarios.acciones": "Acciones",
        "usuarios.editar": "Editar información",
        "usuarios.btn-guardar": "Guardar",
        "usuarios.borrar": "Desactivar usuario",
        "usuarios.ayuda-borrar-0": "¿Está seguro de que desea desactivar esta cuenta de usuario?",
        "usuarios.ayuda-borrar-1": "Todas las cuentas que estén asociadas a ésta también serán desactivadas.",
        "usuarios.btn-borrar": "Desactivar",
        "usuarios.no-datos": "No hay datos",
        "usuarios.tiempo-restante": "Segundos restantes para la prueba de conocimientos",
        "usuarios.etapa-actual": "Etapa actual de su proceso",
        "usuarios.btn-carga-manual": "Manual",
        "usuarios.btn-carga-masivo": "Masivo",
        "usuarios.label-archivos-seleccionados": "Archivos seleccionados",
        "usuarios.btn-cargar-seleccionados": "Cargar archivos seleccionados",
        "usuarios.cargar-ayuda": "Dé click en el <1>botón +</1> en la esquina superior derecha para seleccionar los archivos. Recuerde que sólo se aceptan los formatos <3>.xlsx</3> y <5>.xlsm</5>.",
        "usuarios.carga-encontrados": "Se encontraron <1>{{count}}</1> usuarios.",
        "usuarios.carga-encontrados-opciones": "Se encontraron <1>{{count}}</1> registros. Seleccione el tipo de usuarios cargados:",
        "usuarios.tipo-registro": "Tipo de usuario a registrar",
        "procesos.titulo": "Procesos pasados",
        "procesos.titulo-alt": "Procesos",
        "procesos.total": "Total de procesos realizados:",
        "procesos.fecha-inicio": "Inicio:",
        "procesos.fecha-final": "Finalización:",
        "procesos.version": "Versión:",
        "procesos.resultados": "Resultados de revisión",
        "procesos.prueba-correctas": "Preguntas correctas",
        "procesos.prueba-incorrectas": "Preguntas incorrectas",
        "filtros.categoria": "Categoría",
        "filtros.orden": "Orden",
        "filtros.fecha-finalizacion": "Fecha de finalización",
        "filtros.version": "Versión del instrumento",
        "filtros.descendente": "Descendente",
        "filtros.ascendente": "Ascendente",
        "calificaciones.titulo": "Calificaciones otorgadas",
        "calificaciones.fecha-asignacion": "Fecha de asignación",
        "calificaciones.fecha-calificacion": "Fecha de calificación",
        "calificaciones.titulo-actividad": "Mi actividad",
        "revision.feedback": "Describa el porqué de su decisión",
        "revision.preentrevista-titulo": "Revisión de Pre-entrevista",
        "revision.nombre-evaluado": "Nombre del(a) docente evaluado(a):",
        "revision.preentrevista-ayuda-1": "Señor(a) evaluador(a), a continuación se relacionan las respuestas registradas por el(la) docente.",
        "revision.preentrevista-ayuda-2": "Tenga en cuenta que si se presentan múltiples respuestas, éstas hacen referencia a las respuestas del nivel inmediatamente superior y en el mismo orden.",
        "revision.calificacion-ayuda": "Definición de valores",
        "revision.calificacion-nulo-titulo": "Nulo",
        "revision.calificacion-nulo-ayuda": "No se cuenta con evidencias",
        "revision.calificacion-parcial-titulo": "Parcial",
        "revision.calificacion-parcial-ayuda": "Se cuenta con evidencias de manera incipiente, parcial, o desordenada",
        "revision.calificacion-totalmente-titulo": "Totalmente",
        "revision.calificacion-totalmente-ayuda": "Se cuenta con evidencia clara y consolidada",
        "revision.calificacion-enviar-titulo": "Enviar a entrevista",
        "revision.calificacion-enviar-ayuda": "Debe indagarse más acerca de este descriptor",
        "revision.calificacion-no-iniciado": "No iniciado",
        "revision.calificacion-inicial": "En estado inicial",
        "revision.calificacion-desarrollo": "En desarrollo",
        "revision.calificacion-establecido": "Establecido",
        "revision.calificacion-entrevista": "Para entrevista",
        "revision.calificacion-entrevista-ayuda": "Se requiere ahondar más por medio de una entrevista",
        "revision.descargar-evidencia": "Descargar evidencia adjunta",
        "revision.seleccione-valor": "Seleccione un valor *",
        "revision.enviada": "Revisión enviada",
        "revision.enviada-ayuda": "La calificación ha sido asignada exitosamente.",
        "revision.descriptores-asociados": "Descriptores asociados",
        "revision.practica-niveles": "Niveles educativos a los que está dirigida",
        "revision.practica-rango-edad": "Rango de edad promedia de los participantes",
        "revision.practica-genero": "Género de los participantes",
        "revision.practica-areas": "¿En qué áreas disciplinares hace énfasis su práctica educativa?",
        "revision.practica-calificar": "Formato de calificación",
        "revision.evidencias": "Archivos de evidencias",
        "revision.produccion-retroalimentada": "Producción de un estudiante retroalimentada",
        "revision.produccion-asignar-calificacion": "Asignar calificación",
        "revision.entrevista-titulo": "Sesión de entrevista",
        "revision.entrevista-ayuda": "Señor(a) evaluador(a), a continuación se relacionan los descriptores que deben ser profundizados en la entrevista",
        "revision.entrevista-ayuda-2": "Tenga presente explorar las evidencias que el(la) docente preparará para la sesión de entrevista",
        "revision.entrevista-respuesta-original": "Respuesta original",
        "revision.entrevista-evidencia": "Evidencia requerida",
        "revision.entrevista-calificacion": "Calificación final",
        "revision.encuesta-titulo": "Revisión de Encuesta",
        "revision.encuesta-evaluado": "Nombre del establecimiento educativo evaluado:",
        "revision.encuesta-ayuda": "Señor(a) evaluador(a), a continuación se relacionan las respuestas registradas por el representante del establecimiento educativo",
        "territorios.titulo": "Territorios",
        "territorios.asignar": "Asignar a territorio",
        "territorio.btn-crear": "Crear",
        "territorio.btn-asignar": "Asignar",
        "territorios.crear": "Crear territorio",
        "territorios.administrar": "Lista de territorios",
        "territorios.disponibles": "Territorios disponibles",
        "territorios.nombre": "Nombre del territorio",
        "territorios.padre": "¿Este territorio es una subdivisión de otro?",
        "territorios.ie-ee": "Nombre de la Institución o Establecimiento",
        "territorios.perteneciente": "Territorio al que pertenece",
        "territorios.lista-nombre": "Nombre del territorio",
        "territorios.lista-padre": "Territorio padre",
        "territorios.lista-fecha-creacion": "Fecha de creación",
        "territorios.lista-acciones": "Acciones",
        "territorios.label-editar": "Editar división territorial",
        "territorios.label-desactivar": "Desactivar división territorial",
        "territorios.ayuda-borrar-0": "¿Está seguro de que desea desactivar este territorio?",
        "territorios.ayuda-borrar-1": "Todas las Instituciones, Establecimientos y Docentes que estén asociados a éste también serán desactivados.",
        "captcha.sin-resolver": "Verificación de reCAPTCHA",
        "captcha.sin-resolver-ayuda": 'Dé click sobre la casilla de verificación de reCAPTCHA presentada encima del botón "INGRESAR". Una vez verificada, proceda a dar click sobre el botón nuevamente para ingresar a la plataforma.',
        "dashboardSuperadmin.datos": "Visualización de datos",
        "dashboardSuperadmin.usuarios": "Visualización de usuarios",
        "auditoria.titulo": "Auditoría de usuarios",
        "auditoria.titulo-alt": "Auditoría",
        "auditoria.buscar": "Buscar por nombre de usuario",
        "auditoria.label-ver": "Ver datos",
        "auditoria.label-datos": "Datos relacionados",
        "auditoria.usuarioIncidido": "Usuario incidido",
        "auditoria.archivosRelacionados": "Archivos relacionados",
        "auditoria.pregunta": "Pregunta",
        "auditoria.nombre": "Nombre",
        "auditoria.idNacional": "ID Nacional",
        "auditoria.url": "URL",
        "auditoria.id": "ID",
        "auditoria.respondido": "Respondido",
        "ayuda.title": "Ayuda y PQRS",
        "ayuda.text": 'Por favor diríjase a la plataforma "Requerimientos", proveída por la Pontificia Universidad Javeriana Cali, haciendo click sobre el botón.',
        "ayuda.btn-label": "Ir a Requerimientos",
        "encuestas.titulo": "Encuesta de autoevaluación",
        "encuestas.ayuda": "Por favor responda todas las preguntas que a continuación encontrará. Éstas buscan indagar sobre el estado actual de su establecimiento educativo frente a la apropiación de las TIC. En este sentido, por favor incluya un archivo de evidencias pertinentes para cada una.",
        "encuestas.no-iniciado": "No iniciado",
        "encuestas.estado-inicial": "En estado inicial",
        "encuestas.desarrollo": "En desarrollo",
        "encuestas.establecido": "Establecido",
        "encuestas.adjuntar": "Adjuntar evidencia",
        "encuestas.subido": "Archivo cargado",
        "encuestas.asignar": "Asignar estado",
        "encuestas.enviada": "Encuesta enviada",
        "encuestas.enviada-ayuda": "La información de su encuesta ha sido cargada exitosamente.",
        "encuestas.asignar-delegado": "Asignar",
        "instrumento.titulo": "Consulta y actualización del instrumento",
        "instrumento.titulo-alt": "Instrumento",
        "instrumento.tab-descriptores": "Descriptores",
        "instrumento.tab-encuestas": "Encuestas de autoevaluación",
        "instrumento.tab-prueba": "Prueba de conocimientos",
        "instrumento.tab-preentrevista": "Pre-entrevista",
        "instrumento.btn-actualizar": "Actualizar versión vigente",
        "instrumento.btn-crear": "Crear nueva versión con los cambios",
        "instrumento.crear-si": "Sí, crear nueva versión",
        "instrumento.crear-no": "No, regresar",
        "instrumento.descriptores-codigo": "Código",
        "instrumento.descriptores-contenido": "Contenido",
        "instrumento.encuestas-factor": "Factor",
        "instrumento.encuestas-pregunta": "Pregunta",
        "instrumento.eliminar": "¿Está seguro de que desea eliminar este elemento del instrumento?",
        "instrumento.eliminar-ayuda": "Si éste hace parte del instrumento vigente, el cambio sólo afectará a usuarios que inicien nuevos procesos.",
        "instrumento.eliminar-si": "Sí, eliminar elemento",
        "instrumento.eliminar-no": "No, regresar",
        "instrumento.agregar-opcion-respuesta": "Agregar nueva opción de respuesta",
        "instrumento.crear-opcion-respuesta": "Nueva opción de respuesta",
        "instrumento.crear-si": "Agregar",
        "instrumento.crear-no": "Cancelar",
        "instrumento.respuesta": "Respuesta",
        "instrumento.grupo":  "Grupo",
        "instrumento.subgrupo": "Subgrupo",
        "instrumento.evidencia":  "Evidencia requerida",
        "instrumento.tipo-nivel":  "Nivel de la pregunta",
        "instrumento.tipo-respuesta":  "Tipo de respuesta",
        "instrumento.descriptores":  "Descriptores evaluados",
        "instrumento.nivel-root": "ROOT",
        "instrumento.nivel-middle": "MIDDLE",
        "instrumento.nivel-final": "FINAL",
        "instrumento.preentrevista-nuevo-grupo": "Agregar nuevo grupo",
        "instrumento.answer-radio": "RADIO",
        "instrumento.answer-checkbox": "CHECKBOX",
        "instrumento.answer-input": "INPUT",
        "instrumento.triggered-by": "Es inicializado por la pregunta con ID...",
        "instrumento.trigger-for": "Inicializa la pregunta con ID...",
        "instrumento.respuestas-opciones": "Opciones de respuesta",
        "instrumento.preentrevista-borrar-pregunta": "Borrar pregunta",
        "instrumento.borrar-grupo": "Borrar grupo",
        "instrumento.nueva-pregunta": "Nueva pregunta",
        "instrumento.nuevo-grupo": "Nuevo grupo",
        "cursos.titulo": "Cursos",
        "cursos.title": "Administrar cursos",
        "cursos.label-agregar": "Agregar cursos",
        "cursos.label-actuales": "Cursos actuales",
        "cursos.new-nombre": "Nombre",
        "cursos.new-resumen": "Resumen",
        "cursos.new-mediacion": "Mediación",
        "cursos.new-modalidad": "Modalidad",
        "cursos.modalidad-presencial": "Presencial",
        "cursos.modalidad-virtual": "Virtual",
        "cursos.modalidad-blended": "Blended",
        "cursos.modalidad-cualquiera": "Cualquiera",
        "cursos.new-dedicacion": "Horas de dedicación",
        "cursos.new-ubicacion": "Ubicación",
        "cursos.new-institucion": "Institución",
        "cursos.new-enlace": "Enlace / Link",
        "cursos.new-nivel": "Nivel",
        "cursos.new-competencias": "Competencias",
        "cursos.new-requerimientos": "Requerimientos",
        "cursos.new-descripcion": "Descripción",
        "cursos.new-objetivo-general": "Objetivo general",
        "cursos.new-objetivos-especificos": "Objetivos específicos",
        "cursos.new-descriptores": "Descriptores",
        "cursos.new-descriptores-disenio": "Diseño",
        "cursos.new-descriptores-implementacion": "Implementación",
        "cursos.new-descriptores-evaluacion": "Evaluación",
        "cursos.new-descriptores-conoce": "Conoce",
        "cursos.new-descriptores-utiliza": "Utiliza",
        "cursos.new-descriptores-transforma": "Transforma",
        "cursos.new-contenidos": "Contenidos",
        "cursos.new-metodologia": "Metodología",
        "cursos.new-procedimiento": "Procedimiento",
        "cursos.new-evidencias": "Evidencias de desempeño",
        "cursos.new-criterios": "Criterios de desempeño",
        "cursos.new-observaciones": "Observaciones",
        "cursos.niveles-ib": "Integración básico",
        "cursos.niveles-ia": "Integración avanzado",
        "cursos.niveles-iact": "Integración actualización",
        "cursos.niveles-rb": "Reorientación básico",
        "cursos.niveles-ra": "Reorientación avanzado",
        "cursos.niveles-ract": "Reorientación actualización",
        "cursos.niveles-eb": "Evolución básico",
        "cursos.niveles-ea": "Evolución avanzado",
        "cursos.niveles-eact": "Evolución actualización",
        "cursos.requerimientos-internet": "Internet",
        "cursos.requerimientos-computador": "Computador",
        "cursos.requerimientos-mobile": "Dispositivo móvil",
        "cursos.requerimientos-lms": "LMS",
        "cursos.descriptores-nivel": "Nivel",
        "cursos.descriptores-elemento": "Elemento",
        "cursos.creado": "Curso creado",
        "cursos.creado-ayuda": "El curso ha sido creado exitosamente.",
        "cursos.creado-btn": "Regresar",
        "cursos.crear-btn": "Crear curso",
        "cursos.fecha-creacion": "Fecha de creación",
        "cursos.eliminar-titulo": "Desactivar curso",
        "cursos.eliminar-ayuda-1": "¿Está seguro de que desea desactivar este curso?",
        "cursos.eliminar-ayuda-2": "Esto afectará a todos los usuarios de la plataforma, independientemente de la versión del instrumento actual.",
        "visualizacion.titulo": "Actualmente está previsualizando un usuario",
        "visualizacion.btn": "Regresar a inicio",
    }
}

export default es;