const es = {
    translation: {
        "ID": "ID",
        "si": "Sí",
        "no": "No",
        "caracteres-maximos": "Máximo 400 caracteres",
        "seleccionar-archivo": "Seleccionar archivo",
        "archivo": "Archivo",
        "cancelar": "Cancelar",
        "enviar": "Enviar",
        "opcional": "(opcional)",
        "indice-tic": "Índice de apropiación TIC",
        "docentes": "Docentes",
        "instituciones": "Instituciones Educativas",
        "instituciones-corto": "Instituciones",
        "establecimientos": "Establecimientos Educativos",
        "establecimientos-corto": "Establecimientos",
        "gobiernos": "Gobiernos",
        "barrio": "Barrio",
        "localidad": "Localidad",
        "vereda": "Vereda",
        "corregimiento": "Corregimiento",
        "rural": "Rural",
        "urbana": "Urbana",
        "oficial": "Oficial",
        "privado": "Privado",
        "concesion": "Concesión",
        "nombre": "Nombre",
        "calificacion": "Calificación",
        "descriptor": "Descriptor",
        "descripcion": "Descripción",
        "de": "de",
        "filasPorPagina": "Filas por página",
        "buscar": "Buscar...",
        "editar-calificacion": "Editar calificación",
        "revisar": "Revisar",
        "login.titulo": "Inicio de sesión",
        "login.usuario": "Usuario",
        "login.contrasenia": "Contraseña",
        "login.btn": "Ingresar",
        "titulo.no-login": "Plataforma de Competencias TIC",
        "loginCheck.mensaje-navbar": "Plataforma de competencias TIC",
        "dashboardGobierno.division": "Actualmente viendo datos de:",
        "dashboardGobierno.general": "Información general",
        "dashboardGobierno.indice": "Índice de apropiación TIC",
        "dashboardGobierno.establecimientos": "Establecimientos educativos",
        "dashboardGobierno.docentes": "Docentes",
        "dashboardGobierno.descriptores": "Estado de descriptores",
        "dashboardGobierno.niveles": "Estado de niveles",
        "dashboardGobierno.frecuencia-absoluta": "Frecuencia absoluta",
        "dashboardGobierno.frecuencia-relativa": "Frecuencia relativa",
        "dashboardGobierno.distribucion-relativa": "Distribución relativa",
        "dashboardGobierno.detallada": "Información detallada",
        "dashboardGobierno.ruta": "Ruta de aprendizaje sugerida",
        "visorPerfiles.todos": "Ver todos",
        "visorPerfiles.anteriores": "◀ Anteriores",
        "visorPerfiles.siguientes": "Siguientes ▶",
        "perfil.ingreso": "Último ingreso:",
        "perfil.nunca": "nunca ha ingresado",
        "perfil.ver-detalles": "Ver detalles",
        "perfil.num-docentes": "Número de docentes:",
        "procesoPaso.0": "Registro de datos",
        "procesoPaso.1": "Prueba de conocimiento",
        "procesoPaso.2": "Prácticas educativas",
        "procesoPaso.3": "Pre-entrevista",
        "procesoPaso.3-plural": "Pre-entrevistas",
        "procesoPaso.4": "Entrevista",
        "procesoPaso.4-plural": "Entrevistas",
        "practicas.titulo": "Práctica Educativa",
        "practicas.label-informacion-general": "Información general",
        "practicas.informacion-general": 'A continuación, se le pedirá información sobre una práctica educativa apoyada en TIC. Se entiende por práctica educativa "la actividad o conjunto de actividades intencionalmente diseñadas, implementadas y evaluadas por agentes educativos para favorecer la apropiación de conocimiento". Tenga en cuenta que una práctica educativa puede implicar actividades para explorar conocimientos previos, presentar contenidos, brindar oportunidades de práctica y evaluar el aprendizaje.',
        "practicas.nombre": "Nombre de la práctica educativa",
        "practicas.resenia": "Reseña",
        "practicas.ayuda-resenia": "Mencione brevemente el objetivo de enseñanza, personas a quienes está dirigida la práctica, principales recursos tecnológicos utilizados, generalidad del procedimiento utilizado, resultado o conclusión principal.",
        "practicas.tags": "Palabras clave",
        "practicas.ayuda-tags": "Escriba al menos 5 palabras clave",
        "practicas.btn-agregar": "Agregar",
        "practicas.poblacion": "Población",
        "practicas.ayuda-poblacion": "Personas directamente beneficiadas por la práctica educativa",
        "practicas.niveles": "¿A qué niveles educativos está dirigida la práctica educativa?",
        "practicas.num-personas": "Cantidad de personas",
        "practicas.num-grupos": "Cantidad de grupos",
        "practicas.num-personas-grupo": "Personas por grupo",
        "practicas.ayuda-edad": "En general, ¿Cuál es la edad de los estudiantes que participan en su práctica educativa?",
        "practicas.label-rango": "Seleccione un rango *",
        "practicas.necesidades-especiales": "¿La práctica atiende población con necesidades educativas especiales?",
        "practicas.que-necesidades-especiales": "¿A qué necesidades educativas especiales atiende la práctica educativa?",
        "practicas.seleccione-necesidad-especial": "Seleccione la necesidad especial *",
        "practicas.otras-necesidades-cuales": "¿Cuáles?",
        "practicas.area": "Área Disciplinar",
        "practicas.ayuda-area": "¿En qué áreas disciplinares hace énfasis su práctica educativa apoyada en TIC?",
        "practicas.label-descripcion-detallada": "Descripción detallada de la práctica educativa",
        "practicas.necesidad-problema": "¿A qué necesidad o problema atiende su práctica educativa apoyada en TIC?",
        "practicas.ayuda-necesidad-problema": "Las razones que justifican su práctica.",
        "practicas.principal-objetivo": "¿Cuál es el principal objetivo de aprendizaje de la práctica educativa?",
        "practicas.ayuda-principal-objetivo": "La competencia que espera formar en sus estudiantes al finalizar la práctica educativa.",
        "practicas.label-resultados": "¿Cuáles son los resultados de aprendizaje esperados a partir de la práctica educativa?",
        "practicas.resultados": "Los desempeños y productos de los estudiantes como consecuencia de la participación en la práctica educativa.",
        "practicas.label-actividades": "A continuación, describa la o las actividades que propone para lograr el objetivo de aprendizaje.",
        "practicas.label-actividades-agregadas": "Actividades agregadas",
        "practicas.btn-agregar-actividad": "Agregar actividad",
        "practicas.label-checkbox": "Aseguro que la información proveída es correcta y completa.",
        "practicas.btn-enviar": "Enviar práctica educativa",
        "practicas.label-detalles-actividad": "Detalles de la actividad",
        "practicas.ayuda-detalles-actividad": "Complete los campos mostrados a continuación.",
        "practicas.elemento": "Elemento",
        "practicas.descripcion-contenido": "Descripción del contenido",
        "practicas.actividad-nombre": "Nombre de la actividad",
        "practicas.actividad-proposito": "Propósito",
        "practicas.actividad-modalidad-trabajo": "Modalidad de trabajo *",
        "practicas.actividad-grupal": "Grupal",
        "practicas.actividad-individual": "Individual",
        "practicas.actividad-mixta": "Mixta",
        "practicas.actividad-materiales-educativos": "Materiales educativos",
        "practicas.actividad-escenarios": "Escenarios",
        "practicas.actividad-procedimientos": "Procedimientos",
        "practicas.actividad-consigna": "Consigna",
        "practicas.actividad-evalua": "¿Evalúa las producciones de los estudiantes?",
        "practicas.actividad-label-evaluar-desempenio": "¿Qué hace para evaluar los desempeños de los estudiantes?",
        "practicas.actividad-describa-proceso": "Describa el proceso",
        "practicas.actividad-label-adjunte-evidencias": "Adjunte evidencia(s) de la(s) actividad(es) *",
        "practicas.actividad-ayuda-evidencias": "Sólo se aceptan archivos de imagen, video, audio, .doc, .docx, .xlsm, .xlsx, .pdf, .txt, .ppt y .pptx",
        "practicas.actividad-label-adjunte-produccion": "Adjunte la producción de un estudiante retroalimentada, si la tiene.",
        "practicas.actividad-ayuda-adjunte-produccion": "Recuerde borrar cualquier referencia a la identidad del estudiante.",
        "practicas.actividad-btn-agregar": "Agregar actividad",
        "preentrevista.titulo": "Pre-entrevista",
        "preentrevista.ayuda": "Por favor responda todas las preguntas que a continuación encontrará. Éstas buscan ahondar en su apropiación de compentencias TIC clave de su proceso docente.",
        "404.titulo": "Página no encontrada",
        "404.btn": "Regresar a inicio",
        "prueba.titulo": "Prueba de conocimiento sobre apropiación de las TICs a las prácticas educativas",
        "prueba.label-introduccion": "Introducción",
        "prueba.introduccion": "Esta es una prueba para evaluar el conocimiento acerca del diseño, implementación y evaluación de prácticas educativas con TIC.",
        "prueba.label-instrucciones": "Instrucciones",
        "prueba.instrucciones": "A continuación, encontrará 31 preguntas de opción múltiple con única respuesta. Cada pregunta está constituida por un enunciado y cuatro (4) opciones de respuesta. Seleccione la opción que considere más correcta. Esta prueba debe ser finalizada una vez se inicia. Puede tomarse hasta una hora y treinta minutos (1:30) para responder. La resolución de la prueba es estrictamente individual.",
        "prueba.btn-iniciar": "Iniciar prueba",
        "prueba.titulo-cuestionario": "Cuestionario de preguntas",
        "prueba.btn-enviar": "Enviar respuestas",
        "prueba.label-tiempo": "Tiempo restante:",
        "prueba.label-resultados": "Resultados",
        "prueba.label-ayuda-resultados": "La prueba ha finalizado. A continuación podrá encontrar sus resultados.",
        "prueba.label-correctas": "Preguntas correctas:",
        "prueba.label-incorrectas": "Preguntas incorrectas:",
        "prueba.btn-volver-inicio": "Volver a inicio",
        "registro.titulo-principal": "Registro de datos",
        "registro.titulo": "Datos personales",
        "registro.nombres": "Nombres",
        "registro.apellidos": "Apellidos",
        "registro.fecha-nacimiento": "Fecha de nacimiento",
        "registro.descripcion-personal": "Descripción personal",
        "registro.label-educacion": "Educación formal máxima (alcanzada o en curso) *",
        "registro.educacion-bachiller": "Bachiller",
        "registro.educacion-tecnico": "Técnico",
        "registro.educacion-tecnologo": "Tecnólogo",
        "registro.educacion-profesional": "Tecnólogo",
        "registro.educacion-especialista": "Especialista",
        "registro.educacion-magister": "Magister",
        "registro.educacion-doctorado": "Doctorado",
        "registro.educacion-postdoctorado": "Posdtoctorado",
        "registro.label-anios-experiencia": "¿Cuántos años tiene de experiencia docente?",
        "registro.experiencia-0": "No tengo experiencia",
        "registro.experiencia-1": "Entre 1 y 5",
        "registro.experiencia-2": "Entre 5 y 10",
        "registro.experiencia-3": "Entre 10 y 15",
        "registro.experiencia-4": "Más de 15 años",
        "registro.representa-ie": "¿Representa a una institución educativa? *",
        "registro.cual-label-otra": "Otra",
        "registro.directivo-otra-error": "Por favor consulte con su Insitución Educativa para que primero se realice su registro.",
        "registro.label-directivo": "¿Es directivo docente? *",
        "registro.label-tipo-directivo": "Tipo de directivo docente *",
        "registro.rector": "Rector",
        "registro.director": "Director",
        "registro.coordinador": "Coordinador",
        "registro.label-niveles": "¿En qué niveles enseña?",
        "registro.no-aplica": "No aplica",
        "registro.preescolar": "Preescolar",
        "registro.primaria": "Básica primaria",
        "registro.secundaria": "Básica secundaria",
        "registro.academica": "Media académica",
        "registro.tecnica": "Media técnica",
        "registro.label-areas": "Señale en qué áreas disciplinares trabaja en el establecimiento educativo - puede elegir más de una opción.",
        "registro.naturales": "Ciencias naturales y educación ambiental",
        "registro.sociales": "MeCiencias sociales, historia, geografía y constitución política y democraciadia",
        "registro.arte": "Educación artística y cultural",
        "registro.etica": "Educación ética y en valores humanos",
        "registro.deporte": "Educación física, recreación y deporte",
        "registro.religion": "Educación Religiosa",
        "registro.humanidades": "Humanidades (lengua castellana e idiomas extranjeros)",
        "registro.matematicas": "Matemáticas",
        "registro.informatica": "Tecnología e informática",
        "registro.label-areas-otras": "Otra(s)",
        "registro.areas-otras": "¿Cuál(es)?",
        "registro.label-datos-perfil": "Datos de perfil",
        "registro.usuario": "Usuario",
        "registro.contrasenia": "Contrasenia",
        "registro.label-img-perfil": "Adjunte una imagen de perfil",
        "registro.email": "Correo electrónico",
        "registro.num-contacto": "Número de contacto",
        "registro.web-personal": "Página web personal",
        "registro.btn-guardar": "Guardar datos",
        "entrevista.titulo": "Evidencias requeridas",
        "entrevista.ayuda": "Señor(a) docente, por favor prepare los siguientes recursos para presentar durante su próxima sesión de entrevista.",
        "entrevista.label-no-evaluado": "Su pre-entrevista aún no ha sido evaluada.",
        "entrevista.ayuda-no-evaluado": "Tan pronto se realice este proceso, se le notificará via correo electrónico con los recursos que deberá presentar durante la entrevista. Igualmente, revise periódicamente esta página.",
        "entrevista.no-requerido": "No requiere de entrevista",
        "entrevista.ayuda-no-requerido-0": "Señor(a) docente, tras evaluar su pre-entrevista, se ha determinado que no es necesario que pase a una entrevista.",
        "entrevista.ayuda-no-requerido-1": "Lo invitamos a analizar sus resultados e implementar las acciones de mejora correspondientes.",
        "entrevista.ayuda-no-requerido-2": "Igualmente, a volver a realizar todo el proceso cuando lo considere pertinente, para poder evaluar el progreso de su apropiación en competencias TIC.",
        "dashboardEE.label-docentes": "Estado de docentes",
        "dashboardEE.docentes": "Docentes",
        "dashboardEE.nunca-ingreso": "Nunca han ingresado",
        "dashboardEE.label-estado-general": "Estado general de procesos",
        "dashboardEE.label-frecuencia-absoluta": "Frecuencia absoluta",
        "dashboardEE.label-frecuencia-relativa": "Frecuencia relativa",
        "dashboardEE.ruta": "Ruta de aprendizaje sugerida",
        "dashboardDocente.proceso-actual": "Proceso actual",
        "dashboardDocente.label-continuar": "Continuar con:",
        "dashboardDocente.mensaje-terminado": "Ha terminado el proceso actual exitosamente. Ya puede iniciar otro cuando lo considere conveniente.",
        "dashboardDocente.diagnostico": "Diagnóstico personal",
        "dashboardDocente.resultados-pruebas": "Resultados de pruebas",
        "dashboardDocente.ruta": "Ruta de aprendizaje sugerida",
        "dashboardDocente.no-data": "Aún no hay datos para mostrar",
        "dashboardDocente.acciones": "Acciones",
        "dashboardDocente.btn-registro": "Ver datos personales",
        "dashboardDocente.btn-prueba": "Ver prueba de conocimiento",
        "dashboardDocente.btn-datos": "Ver datos personales",
        "dashboardDocente.btn-practica": "Ver práctica educativa",
        "dashboardDocente.btn-preentrevista": "Ver pre-entrevista",
        "dashboardDocente.btn-entrevista": "Ver entrevista",
        "dashboardEvaluador.asignado-revision": "Asignado para revisión el:",
        "dashboardEvaluador.datos-contacto": "Datos de contacto",
        "configuracion.titulo": "Configuración",
        "configuracion.ajustes-plataforma": "Ajustes de la plataforma",
        "configuracion.label-version": "Versión del instrumento",
        "configuracion.label-idioma": "Idioma de la interfaz",
        "configuracion.ajustes-cuenta": "Información de la cuenta",
        "configuracion.label-imagen": "Imagen de perfil",
        "configuracion.label-usuario": "Nombre de usuario",
        "configuracion.label-contrasenia": "Contraseña",
        "configuracion.label-eliminar": "Desactivar cuenta",
        "configuracion.label-eliminar-confirmacion": "¿Está seguro(a) de que desea desactivar su cuenta?",
        "configuracion.label-eliminar-confirmacion-2": "Todas las cuentas que se encuentren asociadas a la suya también serán desactivadas.",
        "configuracion.label-radio": "Sí, estoy seguro(a) de que quiero desactivar mi cuenta.",
        "configuracion.label-btn-eliminar": "Desactivar mi cuenta",
        "usuarios.label-registro-admins": "Registrar Administradores",
        "usuarios.label-registro-instituciones": "Registrar Instituciones",
        "usuarios.label-usuarios-gobiernos": "Lista de Gobiernos",
        "usuarios.label-usuarios-instituciones": "Lista de Instituciones",
        "usuarios.registro-pais": "País",
        "usuarios.registro-departamento": "Provincia, Estado o Departamento",
        "usuarios.registro-btn-agregar": "Crear usuarios",
        "usuarios.registro-municipio": "Municipio o Ciudad",
        "usuarios.registro-nombre-ie": "Nombre",
        "usuarios.registro-idNacional": "ID Nacional",
        "usuarios.label-registro-establecimientos": "Registrar Establecimientos",
        "usuarios.label-usuarios-establecimientos": "Lista de Establecimientos",
        "usuarios.registro-ee-id": "ID Nacional",
        "usuarios.registro-ee-nombre": "Nombre",
        "usuarios.registro-ee-departamento": "Departamento",
        "usuarios.registro-ee-direccion": "Dirección",
        "usuarios.registro-ee-tipo-ubicacion": "Tipo de ubicación",
        "usuarios.registro-ee-nombre-ubicacion": "Nombre de la ubicación",
        "usuarios.registro-ee-zona": "Zona",
        "usuarios.registro-ee-regimen": "Régimen",
        "usuarios.registro-ee-telefono": "Teléfono",
        "usuarios.registro-ee-email": "Correo electrónico institucional",
        "usuarios.registro-ee-web": "Sitio web",
        "usuarios.label-registro-docentes": "Registrar Docentes",
        "usuarios.label-usuarios-docentes": "Lista de Docentes",
        "usuarios.registro-nombre-docente": "Nombre completo",
        "usuarios.registro-idEstablecimiento": "ID Nacional de la sede a la que pertenece",
        "usuarios.acciones": "Acciones",
        "usuarios.editar": "Editar información",
        "usuarios.btn-guardar": "Guardar",
        "usuarios.borrar": "Desactivar usuario",
        "usuarios.ayuda-borrar-0": "¿Está seguro de que desea desactivar esta cuenta de usuario?",
        "usuarios.ayuda-borrar-1": "Todas las cuentas que estén asociadas a ésta también serán desactivadas.",
        "usuarios.btn-borrar": "Desactivar",
        "usuarios.no-datos": "No hay datos",
        "procesos.titulo": "Procesos pasados",
        "procesos.total": "Total realizados:",
        "procesos.fecha-inicio": "Inicio:",
        "procesos.fecha-final": "Finalización:",
        "procesos.version": "Versión:",
        "procesos.resultados": "Resultados de revisión",
        "procesos.prueba-correctas": "Preguntas correctas",
        "procesos.prueba-incorrectas": "Preguntas incorrectas",
        "filtros.categoria": "Categoría",
        "filtros.orden": "Orden",
        "filtros.fecha-finalizacion": "Fecha de finalización",
        "filtros.version": "Versión del instrumento",
        "filtros.descendente": "Descendente",
        "filtros.ascendente": "Ascendente",
        "calificaciones.titulo": "Calificaciones otorgadas",
        "calificaciones.fecha-asignacion": "Fecha de asignación",
        "calificaciones.fecha-calificacion": "Fecha de calificación",
        "calificaciones.titulo-actividad": "Mi actividad",
    }
}

export default es;